site_name: NdCloud Admin Template Docs
repo_url: https://github.com/buithaibinh/ngcloud-doc
site_author: buithaibinh
pages:
- [index.md, Home]
- [overview.md, 1. Overview]
- [start.md, 2. Getting started]
- [lib.md, 3. 3rd party]
- [changelog.md, 4. Changelog]
- [faq.md, 5. FAQ]
theme: readthedocs
use_directory_urls: false
